/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.system;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 *
 * @author Faiq Shahzad
 */
public class Checkout_Page extends javax.swing.JFrame {

    Transaction_Page transaction_page;
    POS_DataMembers POS_Data;
    DAL DAL_Object;
    Transaction transaction;
    float total;
    float totalWithGST;
    int totalItems;

    /**
     * Creates new form Checkout_Page
     */
    public Checkout_Page(Transaction_Page transaction_page, POS_DataMembers POS_Data, Transaction transaction) {
        this.transaction_page = transaction_page;
        this.POS_Data = POS_Data;
        this.DAL_Object = new DAL();
        this.transaction = transaction;

        this.total = transaction.calculateTotal();
        this.totalWithGST = transaction.calculateTotalWithGST();
        this.totalItems = transaction.calculateTotalItems();

//        this.total = 0;
//        this.totalWithGST = 0;
//        this.totalItems = 0;
        initComponents();

        DefaultTableModel tableModel = (DefaultTableModel) checkoutTable.getModel();

        LinkedList<Item> orderItems = transaction.getOrderItems();

        for (Item i : orderItems) {
            tableModel.insertRow(tableModel.getRowCount(), new Object[]{i.getBarCode(), i.getName(), i.getPrice(), i.getQuantity(), i.getCompany()});
        }

        total_amount_label.setText(Float.toString(total));
        total_amount_gst_label.setText(Float.toString(totalWithGST));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountPaidTextField = new javax.swing.JTextField();
        balanceLabel = new javax.swing.JLabel();
        balance_amount_label = new javax.swing.JLabel();
        doneButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        amountPaidLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        total_amount_label = new javax.swing.JLabel();
        computeBalanceButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        totalGSTLabel = new javax.swing.JLabel();
        total_amount_gst_label = new javax.swing.JLabel();
        checkoutLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amountPaidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountPaidTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(amountPaidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 78, -1));

        balanceLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        balanceLabel.setText("Balance: ");
        getContentPane().add(balanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, -1, -1));

        balance_amount_label.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        balance_amount_label.setText("Enter Amount To Compute Balance");
        getContentPane().add(balance_amount_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        doneButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 90, 30));

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bar Code", "Name", "Price", "Quantity", "Company"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(checkoutTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 506, 384));

        amountPaidLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        amountPaidLabel.setText("Amount Paid:");
        getContentPane().add(amountPaidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        totalLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        totalLabel.setText("Total:");
        getContentPane().add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        total_amount_label.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        total_amount_label.setText("total_amount");
        getContentPane().add(total_amount_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        computeBalanceButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        computeBalanceButton.setText("Compute Balance");
        computeBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBalanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(computeBalanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 190, 40));

        backButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 90, 30));

        totalGSTLabel.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        totalGSTLabel.setText("Include (GST): ");
        getContentPane().add(totalGSTLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, -1));

        total_amount_gst_label.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        total_amount_gst_label.setText("total_amount_gst");
        getContentPane().add(total_amount_gst_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        checkoutLabel.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        checkoutLabel.setText("Checkout");
        getContentPane().add(checkoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        background.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/checkoutBackground.jpg"))); // NOI18N
        background.setText("bg]");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountPaidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountPaidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountPaidTextFieldActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed

        String cashierName = POS_Data.signedInUserFullName;

        DateFormat dateFormat = new SimpleDateFormat("dd/MM/YYYY");
        Date date = new Date();
        Calendar calendar = Calendar.getInstance();

        String dateString = dateFormat.format(date);

        DAL_Object.runQuery("insert into TransactionHistory values (1, '" + cashierName + "', " + Integer.toString(totalItems) + ", " + Float.toString(totalWithGST) + ", '" + dateString + "')");

        transaction_page.dispose();

        this.dispose();

        new Home_Page(POS_Data).setVisible(true);
    }//GEN-LAST:event_doneButtonActionPerformed

    private void computeBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBalanceButtonActionPerformed
        float amountEntered = Float.parseFloat(amountPaidTextField.getText());

        balance_amount_label.setText(Float.toString(amountEntered - totalWithGST));
    }//GEN-LAST:event_computeBalanceButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();

        transaction_page.setVisible(true);

    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout_Page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout_Page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout_Page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout_Page.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout_Page(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountPaidLabel;
    private javax.swing.JTextField amountPaidTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel balance_amount_label;
    private javax.swing.JLabel checkoutLabel;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JButton computeBalanceButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel totalGSTLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel total_amount_gst_label;
    private javax.swing.JLabel total_amount_label;
    // End of variables declaration//GEN-END:variables
}
