/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.system;

/**
 *
 * @author moizs
 */
public class Home_Page extends javax.swing.JFrame {

    POS_DataMembers POS_Data;

    /**
     * Creates new form Home_Page
     */
    public Home_Page(POS_DataMembers POS_Data) {
        this.POS_Data = POS_Data;
        initComponents();

        welcomeLabel.setText("Welcome, " + POS_Data.signedInUserFullName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        startTransactionButton = new javax.swing.JButton();
        headLineLabel = new javax.swing.JLabel();
        editUserButton = new javax.swing.JButton();
        editInventoryButton = new javax.swing.JButton();
        viewTransactionHistoryButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        letsstartselling = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        welcomeLabel.setText("Welcome");
        getContentPane().add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 660, 70));

        startTransactionButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        startTransactionButton.setText("Start Transactions");
        startTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTransactionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startTransactionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 240, 40));

        headLineLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        headLineLabel.setText("Let's Start Selling");
        getContentPane().add(headLineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 240, 40));

        editUserButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        editUserButton.setText("Edit User");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 140, 40));

        editInventoryButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        editInventoryButton.setText("Edit Inventory");
        editInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInventoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editInventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 180, 40));

        viewTransactionHistoryButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        viewTransactionHistoryButton.setText("View Transaction History");
        viewTransactionHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionHistoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewTransactionHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, 40));

        exitButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 90, 40));

        letsstartselling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/homeBackground.jpg"))); // NOI18N
        letsstartselling.setText("homebg");
        getContentPane().add(letsstartselling, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void startTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTransactionButtonActionPerformed
        this.dispose();

        new Transaction_Page(POS_Data).setVisible(true);
    }//GEN-LAST:event_startTransactionButtonActionPerformed

    private void editInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInventoryButtonActionPerformed
        this.dispose();

        new Inventory_Page(POS_Data).setVisible(true);
    }//GEN-LAST:event_editInventoryButtonActionPerformed

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
        this.dispose();

        new Edit_User(POS_Data).setVisible(true);
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void viewTransactionHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionHistoryButtonActionPerformed
        this.dispose();

        new Transaction_History(POS_Data).setVisible(true);
    }//GEN-LAST:event_viewTransactionHistoryButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editInventoryButton;
    private javax.swing.JButton editUserButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel headLineLabel;
    private javax.swing.JLabel letsstartselling;
    private javax.swing.JButton startTransactionButton;
    private javax.swing.JButton viewTransactionHistoryButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
