/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.system;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moizs
 */
public class Inventory_Page extends javax.swing.JFrame {

    POS_DataMembers POS_Data;
    DAL DAL_Object;

    /**
     * Creates new form Inventory_Page
     */
    public Inventory_Page(POS_DataMembers POS_Data) {
        this.POS_Data = POS_Data;
        this.DAL_Object = new DAL();
        initComponents();

        ResultSet resultSet = DAL_Object.runQueryAndGetTable("select * from Inventory");

        try {
            while (resultSet.next()) {
                DefaultTableModel tableModel = (DefaultTableModel) inventoryTable.getModel();

                tableModel.insertRow(tableModel.getRowCount(), new Object[]{resultSet.getInt(1), resultSet.getString(2), resultSet.getFloat(3), resultSet.getInt(4), resultSet.getString(5)});
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        priceTextField = new javax.swing.JTextField();
        barcodeTextField = new javax.swing.JTextField();
        quantityTextField = new javax.swing.JTextField();
        companyTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        removeItemButton = new javax.swing.JButton();
        addItemButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        bg_inventory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryTable.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barcode", "Name", "Price", "Quantity", "Company "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(inventoryTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 480, 230));

        priceTextField.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        priceTextField.setForeground(new java.awt.Color(153, 153, 153));
        priceTextField.setText("Price");
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 110, 40));

        barcodeTextField.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        barcodeTextField.setForeground(new java.awt.Color(153, 153, 153));
        barcodeTextField.setText("Barcode");
        barcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(barcodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 110, 40));

        quantityTextField.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        quantityTextField.setForeground(new java.awt.Color(153, 153, 153));
        quantityTextField.setText("Quantity");
        quantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(quantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 110, 40));

        companyTextField.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        companyTextField.setForeground(new java.awt.Color(153, 153, 153));
        companyTextField.setText("Company");
        companyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(companyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 110, 40));

        nameTextField.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(153, 153, 153));
        nameTextField.setText("Name");
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 110, 40));

        removeItemButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        removeItemButton.setText("Remove Item");
        removeItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeItemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 160, 40));

        addItemButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 130, 40));

        backButton.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 90, 40));

        bg_inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/system/inventoryBackground.jpg"))); // NOI18N
        bg_inventory.setText("jLabel1");
        getContentPane().add(bg_inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    private void companyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void removeItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeItemButtonActionPerformed
        int barcode = (int) inventoryTable.getValueAt(inventoryTable.getSelectedRow(), 0);

        DefaultTableModel tableModel = (DefaultTableModel) inventoryTable.getModel();

        tableModel.removeRow(inventoryTable.getSelectedRow());

        DAL_Object.runQuery("delete from Inventory where barcode=" + Integer.toString(barcode));
    }//GEN-LAST:event_removeItemButtonActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        int barcode = Integer.parseInt(barcodeTextField.getText());
        String name = nameTextField.getText();
        float price = Float.parseFloat(priceTextField.getText());
        int quantity = Integer.parseInt(quantityTextField.getText());
        String company = companyTextField.getText();

        DefaultTableModel tableModel = (DefaultTableModel) inventoryTable.getModel();

        tableModel.insertRow(tableModel.getRowCount(), new Object[]{barcode, name, price, quantity, company});

        DAL_Object.runQuery("insert into Inventory values (" + barcode + ", '" + name + "', " + price + ", " + quantity + ", '" + company + "')");
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();

        new Home_Page(POS_Data).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory_Page(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField barcodeTextField;
    private javax.swing.JLabel bg_inventory;
    private javax.swing.JTextField companyTextField;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton removeItemButton;
    // End of variables declaration//GEN-END:variables
}
